In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
# connect the PostgreSQL database to the model 
# from sqlalchemy import create_engine

## replace user, password, host, port, database, and mytable with local values
# engine = create_engine('postgresql://user:password@host:port/database')

# df = pd.read_sql_query('SELECT * FROM mytable', con=engine)
# df

In [3]:
#### Section 1 ################################################
###############################################################
#### Logistic Regression model ################################
#### 2022 Forbes List Data Only ###############################

In [4]:
# Load the data
df = pd.read_csv("../Billionaire_Analysis/Resources/cleaned_billionaire.csv")
df.head()


rank                personName  age  finalWorth  category  country  \
0     1                 Elon Musk   50      219000         6       49   
1     2                Jeff Bezos   58      171000         2       49   
2     3  Bernard Arnault & family   73      158000        15       71   
3     4                Bill Gates   66      129000         2       49   
4     5            Warren Buffett   91      118000         0       49   

   gender_F  gender_M  
0         0         1  
1         0         1  
2         0         1  
3         0         1  
4         0         1

In [5]:
# List comprehension to add a new column
## Values in column are 1 if the values in "finalWorth" is greater than 4799 and 0 if less than 4799
## $4799.09 is the mean finalWorth amount. Rounded to 4799.
df["finalWorth>4799"] = ["1" if value > 4799 else "0" for value in df["finalWorth"]]
df.head()


rank                personName  age  finalWorth  category  country  \
0     1                 Elon Musk   50      219000         6       49   
1     2                Jeff Bezos   58      171000         2       49   
2     3  Bernard Arnault & family   73      158000        15       71   
3     4                Bill Gates   66      129000         2       49   
4     5            Warren Buffett   91      118000         0       49   

   gender_F  gender_M finalWorth>4799  
0         0         1               1  
1         0         1               1  
2         0         1               1  
3         0         1               1  
4         0         1               1

In [6]:
# Create the feature matrix and the target vector
features = ["rank", "age", "category", "country",
          "gender_F", "gender_M"]

target = ["finalWorth>4799"]


In [7]:
# Create X and y variables
# Create our features
X = df.loc[:, features].copy()

# Create our target
## This calls the target variable from ln[4] 
## and will locate and copy all values within the "finalWorth" column
## Then reshapes y into a flat 1D array
y = df.loc[:, target].copy()
y = y.values.reshape(-1)


In [8]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [9]:
# Create a model object
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs',random_state=1)


In [10]:
from sklearn.preprocessing import StandardScaler
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


In [11]:
# Fit the model
model.fit(X_train_scaled, y_train)


LogisticRegression(random_state=1)

In [12]:
# Predict with the model
y_pred = model.predict(X_test_scaled)


In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
# calculate the confusion matrix and accuracy score
cm = confusion_matrix(y_test, y_pred)
acc_score = accuracy_score(y_test, y_pred)

print("Confusion Matrix:\n", cm)
print("Accuracy Score:", acc_score)


Confusion Matrix:
 [[384   0]
 [  4 128]]
Accuracy Score: 0.9922480620155039


In [14]:
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(cm, 
                     index=["Predicted >4,799", "Predicted <4,799"], 
                     columns=["Actual >4,799", "Actual <4,799"])

cm_df


Actual >4,799  Actual <4,799
Predicted >4,799            384              0
Predicted <4,799              4            128

In [15]:
# Evaluate the model on the test data
accuracy = model.score(X_test_scaled, y_test)
print("Accuracy:", accuracy)


Accuracy: 0.9922480620155039


In [16]:
#### Section 2 ################################################
###############################################################
#### Add more data to the Logistic Regression model ###########
#### 2022 & 2018 Forbes List Data #############################


In [17]:
# Add the extra data
df2 = pd.read_csv("../Billionaire_Analysis/Resources/cleaned_2018_billionaire.csv")
df2.head()


rank       personName  age  finalWorth  category  country  gender_F  \
0     1       Jeff Bezos   54      112000         9       71         0   
1     2       Bill Gates   62       90000         9       71         0   
2     3   Warren Buffett   87       84000        15       71         0   
3     4  Bernard Arnault   69       72000        17        4         0   
4     5  Mark Zuckerberg   33       71000         9       71         0   

   gender_M  
0         1  
1         1  
2         1  
3         1  
4         1

In [18]:
# List comprehension to add a new column
## Values in column are 1 if the values in "finalWorth" is greater than 4799 and 0 if less than 4799
## $4799.09 is the mean finalWorth amount. Rounded to 4799.
df2["finalWorth>4799"] = ["1" if value > 4799 else "0" for value in df2["finalWorth"]]
df2.head()


rank       personName  age  finalWorth  category  country  gender_F  \
0     1       Jeff Bezos   54      112000         9       71         0   
1     2       Bill Gates   62       90000         9       71         0   
2     3   Warren Buffett   87       84000        15       71         0   
3     4  Bernard Arnault   69       72000        17        4         0   
4     5  Mark Zuckerberg   33       71000         9       71         0   

   gender_M finalWorth>4799  
0         1               1  
1         1               1  
2         1               1  
3         1               1  
4         1               1

In [19]:
# target and features stay the same
features = ["rank", "age", "category", "country","gender_F", "gender_M"]

target = ["finalWorth>4799"]


In [20]:
# Join the 2018 and 2022 datasets together
## Since this is joining two lists together, "rank" and "personName" may have repeating values
df_2022_2018 = pd.concat([df,df2])
df_2022_2018


rank                personName  age  finalWorth  category  country  \
0        1                 Elon Musk   50      219000         6       49   
1        2                Jeff Bezos   58      171000         2       49   
2        3  Bernard Arnault & family   73      158000        15       71   
3        4                Bill Gates   66      129000         2       49   
4        5            Warren Buffett   91      118000         0       49   
...    ...                       ...  ...         ...       ...      ...   
2130  2124            Zhao Xiaoqiang   50        1000        17       17   
2131  2124           Zhou Liangzhang   55        1000         0       17   
2132  2124              Zhu Xingming   51        1000         0       17   
2133  2124                  Zhuo Jun   52        1000         0       18   
2134  2124               Olgun Zorlu   54        1000         5       48   

      gender_F  gender_M finalWorth>4799  
0            0         1               1  
1            0         1               1  
2            0         1               1  
3            0         1               1  
4            0         1               1  
...        ...       ...             ...  
2130         0         1               0  
2131         0         1               0  
2132         0         1               0  
2133         1         0               0  
2134         0         1               0  

[4711 rows x 9 columns]

In [21]:
# Create X and y variables
# Create our features
X = df_2022_2018.loc[:, features].copy()

# Create our target
y = df_2022_2018.loc[:, target].copy()
y = y.values.reshape(-1)


In [22]:
# Split the data into training and testing. Updated test_size to 0.3.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [23]:
# Create the model object
model = LogisticRegression(solver='lbfgs',random_state=1)


In [24]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


In [25]:
# Fit the model
model.fit(X_train_scaled, y_train)


LogisticRegression(random_state=1)

In [26]:
# Predict with the model
y_pred = model.predict(X_test_scaled)


In [27]:
# calculate the confusion matrix and accuracy score
cm = confusion_matrix(y_test, y_pred)
acc_score = accuracy_score(y_test, y_pred)

print("Confusion Matrix:\n", cm)
print("Accuracy Score:", acc_score)


Confusion Matrix:
 [[723  20]
 [ 12 188]]
Accuracy Score: 0.9660657476139979


In [28]:
# Scale the Xtraining data and show shape to prove it is now a 1D object
X_train_scaled = np.arange(0,len(X_train),1)
X_train_scaled.shape


(3768,)

In [29]:
# Evaluate the model on the test data
accuracy = model.score(X_test_scaled, y_test)
print("Accuracy:", accuracy)


Accuracy: 0.9660657476139979


In [30]:
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(cm, 
                     index=["Predicted >4,799", "Predicted <4,799"], 
                     columns=["Actual >4,799", "Actual <4,799"])

cm_df


Actual >4,799  Actual <4,799
Predicted >4,799            723             20
Predicted <4,799             12            188

In [31]:
# Evaluate the model on the test data
accuracy = model.score(X_test_scaled, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9660657476139979


In [32]:
#### Section 3 ################################################
###############################################################
#### We have to remove rank to see if the other features can ## 
#### hold up the model on their own ###########################
#### Restart the Logistic Regression model ####################
#### 2022 Forbes List Data Only ###############################


In [33]:
# Create the feature matrix and the target vector
features = ["age", "category", "country",
          "gender_F", "gender_M"]

target = ["finalWorth>4799"]


In [34]:
# Create X and y variables
# Create our features
X = df.loc[:, features].copy()

# Create our target
## This calls the target variable from ln[4] 
## and will locate and copy all values within the "finalWorth" column
## Then reshapes y into a flat 1D array
y = df.loc[:, target].copy()
y = y.values.reshape(-1)


In [35]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [36]:
# Create a model object
model = LogisticRegression(solver='lbfgs',random_state=1)


In [37]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


In [38]:
# Fit the model
model.fit(X_train_scaled, y_train)


LogisticRegression(random_state=1)

In [39]:
# Predict with the model
y_pred = model.predict(X_test_scaled)


In [40]:
# calculate the confusion matrix and accuracy score
cm = confusion_matrix(y_test, y_pred)
acc_score = accuracy_score(y_test, y_pred)

print("Confusion Matrix:\n", cm)
print("Accuracy Score:", acc_score)


Confusion Matrix:
 [[397   0]
 [119   0]]
Accuracy Score: 0.7693798449612403


In [41]:
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(cm, 
                     index=["Predicted >4,799", "Predicted <4,799"], 
                     columns=["Actual >4,799", "Actual <4,799"])

cm_df


Actual >4,799  Actual <4,799
Predicted >4,799            397              0
Predicted <4,799            119              0

In [42]:
# Evaluate the model on the test data
accuracy = model.score(X_test_scaled, y_test)
print("Accuracy:", accuracy)


Accuracy: 0.7693798449612403


In [43]:
#### Section 4 ################################################
###############################################################
#### We have to remove rank to see if the other features can ##
#### hold up the model on their own ###########################
#### Restart the Logistic Regression model ####################
#### 2022 & 2018 Forbes List Data #############################


In [44]:
# Create the feature matrix and the target vector
features = ["age", "category", "country",
          "gender_F", "gender_M"]

target = ["finalWorth>4799"]


In [45]:
# Create X and y variables
# Create our features
X = df_2022_2018.loc[:, features].copy()

# Create our target
y = df_2022_2018.loc[:, target].copy()
y = y.values.reshape(-1)


In [46]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [47]:
# Create a model object
model = LogisticRegression(solver='lbfgs',random_state=1)


In [48]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


In [49]:
# Fit the model
model.fit(X_train_scaled, y_train)


LogisticRegression(random_state=1)

In [50]:
# Predict with the model
y_pred = model.predict(X_test_scaled)


In [51]:
# calculate the confusion matrix and accuracy score
cm = confusion_matrix(y_test, y_pred)
acc_score = accuracy_score(y_test, y_pred)

print("Confusion Matrix:\n", cm)
print("Accuracy Score:", acc_score)


Confusion Matrix:
 [[759   0]
 [184   0]]
Accuracy Score: 0.8048780487804879


In [52]:
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(cm, 
                     index=["Predicted >4,799", "Predicted <4,799"], 
                     columns=["Actual >4,799", "Actual <4,799"])

cm_df


Actual >4,799  Actual <4,799
Predicted >4,799            759              0
Predicted <4,799            184              0

In [53]:
# Evaluate the model on the test data
accuracy = model.score(X_test_scaled, y_test)
print("Accuracy:", accuracy)


Accuracy: 0.8048780487804879


In [54]:
#### Section 5 ################################################
###############################################################
#### We can use a random forest ensemble model to rank the ####
#### importance of the features ###############################
###############################################################
#### Random Forest Ensemble Model #############################
#### 2022 Forbes List Data Only ###############################


In [55]:
# Create the feature matrix and the target vector
features = ["age", "category", "country",
          "gender_F", "gender_M"]

target = ["finalWorth>4799"]


In [56]:
# Create X and y variables
# Create our features
X = df.loc[:, features].copy()

# Create our target
## This calls the target variable from ln[4] 
## and will locate and copy all values within the "finalWorth" column
## Then reshapes y into a flat 1D array
y = df.loc[:, target].copy()
y = y.values.reshape(-1)


In [57]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [58]:
from sklearn.ensemble import RandomForestClassifier
# Create a random forest classifier model object
rf_model = RandomForestClassifier(n_estimators=128, random_state=78) 


In [59]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


In [60]:
# Fit the model
rf_model = rf_model.fit(X_train_scaled, y_train)


In [61]:
# Make predictions using the testing data
predictions = rf_model.predict(X_test_scaled)


In [62]:
# calculate the confusion matrix and accuracy score
cm = confusion_matrix(y_test, predictions)
acc_score = accuracy_score(y_test, predictions)

print("Confusion Matrix:\n", cm)
print("Accuracy Score:", acc_score)


Confusion Matrix:
 [[336  61]
 [ 93  26]]
Accuracy Score: 0.7015503875968992


In [63]:
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(cm, 
                     index=["Predicted >4,799", "Predicted <4,799"], 
                     columns=["Actual >4,799", "Actual <4,799"])

cm_df


Actual >4,799  Actual <4,799
Predicted >4,799            336             61
Predicted <4,799             93             26

In [64]:
# print the classification report
print("Classification Report")
print(classification_report(y_test, predictions))


Classification Report
              precision    recall  f1-score   support

           0       0.78      0.85      0.81       397
           1       0.30      0.22      0.25       119

    accuracy                           0.70       516
   macro avg       0.54      0.53      0.53       516
weighted avg       0.67      0.70      0.68       516



In [65]:
# Calculate feature importances
importances = rf_model.feature_importances_
importances


array([0.49291083, 0.23655077, 0.25443165, 0.00807051, 0.00803624])

In [66]:
# Sort the feature importances
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)


[(0.49291082959567356, 'age'),
 (0.2544316524813724, 'country'),
 (0.23655076699964664, 'category'),
 (0.008070509985127053, 'gender_F'),
 (0.008036240938180318, 'gender_M')]

In [67]:
#### Section 6 ################################################
#### We can use a random forest ensemble model to rank the ####
#### importance of the features ###############################
###############################################################
#### Random Forest Ensemble Model #############################
#### 2022 & 2018 Forbes List Data #############################


In [68]:
# Create the feature matrix and the target vector
features = ["age", "category", "country",
          "gender_F", "gender_M"]

target = ["finalWorth>4799"]


In [69]:
# Create X and y variables
# Create our features
X = df_2022_2018.loc[:, features].copy()

# Create our target
y = df_2022_2018.loc[:, target].copy()
y = y.values.reshape(-1)


In [70]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [71]:
# Create a random forest classifier model object
rf_model = RandomForestClassifier(n_estimators=128, random_state=78) 


In [72]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


In [73]:
# Fit the model
rf_model = rf_model.fit(X_train_scaled, y_train)


In [74]:
# Make predictions using the testing data
predictions = rf_model.predict(X_test_scaled)


In [75]:
# calculate the confusion matrix and accuracy score
cm = confusion_matrix(y_test, predictions)
acc_score = accuracy_score(y_test, predictions)

print("Confusion Matrix:\n", cm)
print("Accuracy Score:", acc_score)


Confusion Matrix:
 [[681  82]
 [143  37]]
Accuracy Score: 0.7613997879109226


In [76]:
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(cm, 
                     index=["Predicted >4,799", "Predicted <4,799"], 
                     columns=["Actual >4,799", "Actual <4,799"])

cm_df


Actual >4,799  Actual <4,799
Predicted >4,799            681             82
Predicted <4,799            143             37

In [77]:
# print the classification report
print("Classification Report")
print(classification_report(y_test, predictions))


Classification Report
              precision    recall  f1-score   support

           0       0.83      0.89      0.86       763
           1       0.31      0.21      0.25       180

    accuracy                           0.76       943
   macro avg       0.57      0.55      0.55       943
weighted avg       0.73      0.76      0.74       943



In [78]:
# Calculate feature importances
importances = rf_model.feature_importances_
importances


array([0.46895196, 0.24480973, 0.27238074, 0.00719279, 0.00666478])

In [79]:
# Sort the feature importances
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)


[(0.4689519566609308, 'age'),
 (0.272380742139685, 'country'),
 (0.2448097258310422, 'category'),
 (0.0071927929164195305, 'gender_F'),
 (0.006664782451922373, 'gender_M')]